### ISSUE TITLE
Ambiguitas diftong atau hamzah

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-web#1]
Beberapa contoh kasus: 

- "fainna" yang dikodekan jadi "FAYNA" karena "AI" => "AY" padahal maksudnya (فَإِنَّ) fa-inna
- "faulaika" yang dikodekan jadi "FAWLAYKA" karena "AU" => "AW" padahal maksudnya (فَأُولَئِكَ) fa-ula-ika

Bisa tertangani kalau user memisahkan kedua vokal dengan spasi ("fa inna", "fa ula ika"). Tapi kalau user gak pakai spasi, jadinya salah.

Sama juga kalau misalnya "waamma", algoritme tidak bisa bedakan itu maksudnya "wa-amma" atau "wamma" dengan "a" panjang.

**Comment by isnanmulia** [comment]
Mungkin bisa diakali dengan pengodean ganda.
Misal, input "fainna" akan menjadi 2 kode, yaitu "FAYNA" & "FAINA". Nanti hasil pencarian akan mengambalikan ayat2 yang sesuai dengan "FAYNA" atau "FAINA".
Tapi cara ini akan berpengaruh terhadap performansi, karena proses pencarian akan dilakukan sebanyak variasi kode yang mungkin dari string input.
*CMIIW

**Comment by abrari** [comment]
Yeah, @ariefsam juga nyaranin begitu. Tapi kalo semua kemungkinan harus dicari, pencarian bakal eksponensial (2^n).

Makanya mungkin di indeksnya aja yang dibikin banyak, bukan pas search.

**Comment by rahmanda** [comment]
Btw sebelumnya apa alasannya 'AI' dikodekan jadi 'AY' ya @abrari? Saya pribadi belum pernah membaca terjemahan latin Al-Quran versi Indonesia yang vokal 'I'-nya disamakan dengan 'Y' (atau 'U' dengan 'W').

**Comment by abrari** [comment]
Karena ketika orang menulis AI bisa jadi maksud dia adalah huruf berharokat A disambung dengan YA mati. Jadi AI => AY. Dan harus mengakomodasi semua kemungkinan. Kan ada saja orang yang menuliskan misal "WA'ALAYKUM". Ada juga misal yang menuliskan "QAWMUN".

Bisa lihat-lihat gimana variasi orang menuliskannya dari hasil kuesioner pas riset tentang ini: https://docs.google.com/spreadsheets/d/1d6OGeot78MV4YCAlQ4QeU7S9MoXMcaOWi0C6bAoMT5A/edit?usp=sharing

**Comment by abrari** [comment]
Sudah coba ditangani di lafzi/lafzi-indexer#4, tapi belum live

**Comment by abrari** [comment]
Sekarang sudah live di lafzi.apps.cs.ipb.ac.id
